Hw03
wal1m/nodejs-homework-rest-api pull request #2
Opened 2021-05-23 10:59 UTC by wal1m

Поверьте пожалуйста

2021-05-23 19:22 UTC, SergeiKBB requested changes

2021-05-23 19:22 UTC, SergeiKBB commented on .env
> +URI_DB=mongodb+srv://goit24:098765123456@cluster0.kpaai.mongodb.net/GoIt?retryWrites=true&w=majority
файл должен быть добавлен в гитигнор и удален с ремоут репозитория

2021-05-24 10:26 UTC, wal1m commented
Исправил

2021-05-25 15:12 UTC, sfounder approved these changes

2021-05-26 06:00 UTC, merged